name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-health-management-app:latest .

      - name: Push Docker image
        run: |
          docker push my-health-management-app:latest  # Optional, if you still want to push to Docker Hub

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-193-158-129.us-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@ec2-54-193-158-129.us-west-1.compute.amazonaws.com "
            cd /path/to/your/app &&  # Change this to your app directory
            git pull origin master &&  # Pull the latest code
            docker build -t my-health-management-app:latest . &&
            docker run -d --rm --name my-health-management-app my-health-management-app:latest
          "
