name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sholly333/my-docker-image:latest .

      - name: Push Docker image
        run: |
          docker push sholly333/my-docker-image:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-193-158-129.us-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@ec2-54-193-158-129.us-west-1.compute.amazonaws.com "docker pull sholly333/my-health-management-app:latest && docker run -d --rm --name my-health-management-app sholly333/my-health-management-app:latest"
